config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root "recipes#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # mms: expected to see authentication occur here, to lock down all actions unless logged in.
  # mms:   You are using `current_user` throughout your other controllers, you only have a `current_user` if you are logged in, you need some code to require you to log in.
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:edit, :show, :update, :destroy]

  def index
    if current_user
      # mms: use the current_user's recipes
      @recipe = current_user.recipes
    else
      @recipe = Recipe.all.order("created_at DESC")
    end
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    # mms: use the current_user's recipes
    @recipe = current_user.recipes.build(recipe_params)
     if @recipe.save
       redirect_to @recipe, notice: "Successfully created new recipe"
     else
       # TODO: add view helpers to display errors
       render :new

     end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to @recipe
  end

  # mms: action is delete
  def delete
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :photo_url, :instructions, :ingredients)
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheikhHealthyRecipesPj2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- mms: watch the indentation -->
        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <h3>Healthy Recipes</h3>
            </div>
            <div class="nav navbar-nav navbar-right">
                <li>
                  <%= button_to "Home", root_path, method: :get %>
                </li>
                <li>
              <%= button_to "Signup",  new_user_registration_path, method: :get %>
                </li>

                <% if user_signed_in? %>
                <li>
                  Signed in as <%= current_user.email %>!
                </li>

                <li>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete %>
                </li>

                <% else %>
                <li>
                  <%= button_to "Login",  new_user_session_path %>
                </li>

                <% end %>
            </div>
          </div>
        </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
</body>
</html>

app/views/recipes/_form.html.erb
<!-- mms: We discussed displaying @recipe error messages here.  -->

<%= simple_form_for @recipe do |f| %>
  <%= f.input :title, label: 'Recipe title please', error: 'Title is mandatory, please specify one' %>
  <%= f.input :description, placeholder: 'Enter some description' %>
  <%= f.input :photo_url, placeholder: 'copy and paste a photo url' %>
  <%= f.input :instructions, placeholder: 'put your instructions here'  %>
  <%= f.button :submit %>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipes</h1>

<%= render "form" %>

app/views/recipes/index.html.erb
<div id="front">
  <h1 id="tagline">Eat Healthy. Be Happy</h1>
</div>

<% if current_user %>
  <%= button_to "add a recipe", new_recipe_path, method: :get %>
<% else %>
<%  end %>

  <ul>
    <% @recipe.each do |recipe| %>
        <div class="photo">
        <!-- mms: Good job with an image as a link -->
        <%= link_to(image_tag(recipe.photo_url), recipe) %>
        <!-- <%= link_to recipe.title, recipe %> -->
        </div>
    <% end %>
  </ul>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>
<br>
<!-- mms: why a button instead of a link? -->
<%= button_to "Home page", root_path, method: :get %>

app/views/recipes/show.html.erb
<h1>
  <%= @recipe.title %> <br
</h1>
<!-- mms: watch the indentation.  It would help me understand the logic in this entire page. -->
  <br>
<h2>
  Description
</h2>
  <br>
  <%= @recipe.description %>

<h2>Instructions</h2>
  <br>
  <%= @recipe.instructions %>
  <img class='recipe-photo' src="<%= @recipe.photo_url %>"><br>
  <br>
<div class="button">
    <%= button_to "Back", root_path, method: :get %>
  <br>
    <% if current_user %>
    <% if current_user.id == @recipe.user_id %>
    <%= button_to "Edit", edit_recipe_path, method: :get %>
  <br>
    <%= button_to "Delete", recipe_path(@recipe),method: :delete, data: {confirm: "Are you sure you want to delete your recipe?"}, class: 'delete' %>
</div>
    <% end %>
<% end %>